// src/gxzjt-angular/src/app/index/laws-and-regulations/laws-and-regulations.component.ts
import { Component, OnInit } from '@angular/core';
import { HomeServiceProxy, PageSize } from '@shared/service-proxies/service-proxies';

@Component({
  selector: 'app-laws-and-regulations',
  templateUrl: './laws-and-regulations.component.html',
  styleUrls: ['./laws-and-regulations.less']
})
export class LawsAndRegulationsComponent implements OnInit {
  record: any = {};
  i: any;
  router: any;

  constructor(private _homeService: HomeServiceProxy) { }
  currentIndex = 0;

  downLoadList;

  pageSize: PageSize = new PageSize();
  ngOnInit(): void {
    this.init()
  }
  init() {
    this.pageSize.page = 1;
    this.pageSize.size = 10;
    this._homeService.homeRegulationList(this.pageSize).subscribe(data => {
      this.downLoadList = data.data;
      console.log(this.downLoadList);
    })
  }

  close() { }


  /**
   * 跳转进表单列表页
   */
  goFromList(item) {
    this.router.navigate(item.path);
  }

}

<div id="wrap">
  <div nz-row style="padding: 10px 40px;box-sizing: border-box">
    <div class="content" style="font-size: 8px">
      <span>建设大厅</span> >
      <span style="color: red">法律法规</span>
    </div>
  </div>
  <div nz-row nzGutter="16" style="padding: 0px 40px;box-sizing: border-box;">
    <div class="content">
      <div nz-col nzSpan="24">
        <nz-card nz-card style="font-size:8px;">
          <div style="position: relative;">
            <img style="width: 100%;" src="../../../assets/images/index/法律法规_03.jpg" alt="">
          </div>
        </nz-card>
      </div>
      <div nz-col nzSpan="24">
        <nz-spin [nzSpinning]="!downLoadList">
          <nz-card nz-card style="font-size:8px;">
            <p class="titleLeft"><span>法律法规</span></p>
            <div nz-row nzGutter="50" style="padding:10px 40px 40px 0px;box-sizing: border-box;" *ngIf="downLoadList">
              <ul>
                <li *ngFor="let item of downLoadList">
                  <div style="overflow: hidden"> <span class="title">{{item.title}}</span>
                    <span class="time">{{item.issueOrg}}</span></div>
                  <div style="overflow: hidden;margin-top: 6px;"> <span
                      style="float: right;font-size: 8px">{{item.creationTime|timeNewString}}</span></div>
                </li>
              </ul>
            </div>
          </nz-card>
        </nz-spin>
      </div>
      <!-- <div nz-col nzSpan="12">
        <nz-card nz-card style="font-size:8px;">
         <div style="overflow: hidden"> <p class="titleRight" style="float: right"><span>规范性文件</span></p></div>
          <div nz-row nzGutter="50" style="padding:10px 40px 40px 0px;box-sizing: border-box;">
              <ul>
                  <li *ngFor="let item of downLoadList">
                   <div style="overflow: hidden;"> <span class="title">{{item.name}}</span>
                     <span class="time">{{item.time}}</span></div>
                     <div style="overflow: hidden;margin-top: 6px;"> <span style="float: right;font-size: 8px">{{item.forms}}</span></div>
                  </li>
                </ul>
             </div>
        </nz-card>
      </div> -->
    </div>
  </div>
</div>

// src/indexProject/src/views/laws-and-regulations.vue
<!--  -->
<template>
  <div style="width:100%;overflow:hidden;margin-bottom: 20px;">
    <div class="content">
      <div ref="banner">
        <img style="width:100%;" src="../assets/images/法律法规_03.jpg" alt>
      </div>
      <el-row :gutter="16">
        <el-col :span="12">
          <el-card v-loading="!lawsList" :style="{minHeight:tableHight}">
            <div style="overflow:hidden;">
              <p class="tips" style="float: left">
                <img src="../assets/images/img_bg_flfg.png" alt>
                <span>法律法规</span>
              </p>
            </div>
            <ul class="listParent">
              <li v-for="(item,index) in lawsList" :key="index" class="list">
                <router-link :to="'/laws-and-regulations/detail/'+item.id">
                  <div style="overflow: hidden">
                    <span class="title">{{item.title}}</span>
                    <span class="time">{{item.creationTime}}</span>
                  </div>
                  <div style="overflow: hidden;margin-top: 6px;">
                    <span style="float: right;font-size: 8px">————&nbsp;{{item.issueOrg}}</span>
                  </div>
                </router-link>
              </li>
            </ul>
            <el-row style="margin-top:40px;margin-bottom:25px;">
              <el-pagination
                style="float:right;"
                :page-size="lawPageSize.size"
                layout="prev, pager, next"
                :total="lawtotalCount"
                @current-change="changeCurrent($event,'Regulation')"
              ></el-pagination>
            </el-row>
          </el-card>
        </el-col>
        <el-col :span="12">
          <el-card v-loading="!lawsFiles" :style="{minHeight:tableHight}">
            <div style="overflow:hidden;">
              <p class="tips" style="float: right">
                <img src="../assets/images/法律法规_03.png" alt>
                <span>规范性文件</span>
              </p>
            </div>
            <ul class="listParent">
              <li v-for="(item,index) in lawsFiles" :key="index" class="list">
                <router-link :to="'/laws-and-regulations/detail/'+item.id">
                  <div style="overflow: hidden">
                    <span class="title">{{item.title}}</span>
                    <span class="time">{{item.creationTime}}</span>
                  </div>
                  <div style="overflow: hidden;margin-top: 6px;">
                    <span style="float: right;font-size: 8px">————&nbsp;{{item.issueOrg}}</span>
                  </div>
                </router-link>
              </li>
            </ul>
            <el-row style="margin-top:40px;margin-bottom:25px;">
              <el-pagination
                style="float:right;"
                :page-size="filePageSize.size"
                layout="prev, pager, next"
                :total="filetotalCount"
                @current-change="changeCurrent($event,'Normative')"
              ></el-pagination>
            </el-row>
          </el-card>
        </el-col>
      </el-row>
    </div>
  </div>
</template>

<script>
import { app } from "../assets/js/app";
import { laws } from "../assets/js/apiValue";
import moment from "moment";
export default {
  data() {
    return {
      lawsList: null,
      lawsFiles: null,
      tableHight: "200px",
      lawPageSize: app.pageSize,
      filePageSize: app.pageSize,
      lawtotalCount: 0,
      filetotalCount: 0
    };
  },

  components: {},

  computed: {},

  mounted() {
    this.getlawsList();
    this.getFileList();
    const that = this;
    setTimeout(function() {
      that.tableHight =
        app.clentHeight() - that.$refs.banner.offsetHeight + "px";
    }, 100);
    window.onresize = function() {
      that.tableHight = app.clentHeight() + "px";
    };
  },

  methods: {
    //获取法律法规文件
    getlawsList() {
      let _this = this;
      _this.lawsList = [];
      let lawParams = Object.assign({ group: "Regulation" }, this.lawPageSize);
      app.post(laws.serach_lawsList, lawParams).then(req => {
        if (req.success) {
          req.result.data.forEach(element => {
            element.creationTime = moment(element.creationTime).format(
              "YYYY-MM-DD hh:mm:ss"
            );
          });
          _this.lawsList = req.result.data;

          _this.lawtotalCount = req.result.totalCount;
        }
      });
    },
    /**
     *
     * 获取规范性文件
     */
    getFileList() {
      let _this = this;
      _this.lawsFiles = [];
      let fileParams = Object.assign({ group: "Normative" }, this.filePageSize);
      app.post(laws.serach_lawsList, fileParams).then(req => {
        if (req.success) {
          req.result.data.forEach(element => {
            element.creationTime = moment(element.creationTime).format(
              "YYYY-MM-DD hh:mm:ss"
            );
          });
          _this.lawsFiles = req.result.data;
          _this.filetotalCount = req.result.totalCount;
        }
      });
    },
    changeCurrent(page, type) {
      if (type == "Regulation") {
        this.lawPageSize.page = page;
        this.getlawsList();
      } else if (type == "Normative") {
        this.filePageSize.page = page;
        this.getFileList();
      }
      console.log(type);
      console.log(page);
    }
  }
};
</script>
<style lang='less' scoped>
.title {
  float: left;
}
.time {
  float: right;
}
.tip {
  width: 32%;
  padding: 5px 0;
  text-indent: 20%;
  background-repeat: no-repeat;
  background-position: left;
  font-size: 22px;
  color: #fff;
}
</style>
